In [20]:
import numpy

In [21]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [22]:
#Reshapes the n-dimensional array into (x,y) x-dimensions and each dimension has y number of values in it!
print(n.reshape(3,9))

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [23]:
print(n.reshape(3,3,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


-----
**Converting images to Numpy Arrays**

In [25]:
# Image path: "C:\\Users\\fabio\\Jupyter-notebooks\\ds-python-examples\\data\\smallgray.png"
# Image has only 15px!

In [26]:
!pip install opencv-python

In [27]:
import cv2

In [34]:
# if the second parameter is:
#    0 => you read the image in as greyscale
#    1 => you read the image in as bgr(blue, green, red)
im_g=cv2.imread("C:\\Users\\fabio\\Jupyter-notebooks\\ds-python-examples\\data\\smallgray.png", 0) 
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
im_rgb=cv2.imread("C:\\Users\\fabio\\Jupyter-notebooks\\ds-python-examples\\data\\smallgray.png", 1) 
im_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

--------
**Converting back an Numpy ndarray to an image**

In [36]:
# Second parameter of the imwrite-method means the same as the imread-method!
cv2.imwrite("C:\\Users\\fabio\\Jupyter-notebooks\\ds-python-examples\\data\\new_small_gray.png", 0)

True

In [37]:
cv2.imwrite("C:\\Users\\fabio\\Jupyter-notebooks\\ds-python-examples\\data\\new_small_rgb.png", 1)

True

------------
**Indexing, Slicing and Iterating Numpy Arrays**

In [39]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [40]:
im_g[0:2] #Index for the rows ...

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [41]:
im_g[0:2, 2:4]# Index for the columns

array([[104, 121],
       [255, 255]], dtype=uint8)

In [42]:
im_g[:, 2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [43]:
im_g[2,4] # Getting one value

182

In [48]:
for i in im_g.T:
    print(i)
    for y in i.T:
        print(y)

[187 198 209]
187
198
209
[158 125 134]
158
125
134
[104 255 255]
104
255
255
[121 255  97]
121
255
97
[143 147 182]
143
147
182


In [49]:
#Better and Simpele:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182



-----
**Stacking and Splitting Numpy Arrays**

In [58]:
#To join Numpy Arrays > 2 methods:
#    Horizontal-Stack: numpy.hstack((ary1, ary2, ...)) A Tuple of two or more arrays is the param
#    Vertical-Stack: numpy.vstack((ary1, ary2, ...)) A Tuple of two or more arrays is the param

# !!!!!!!!!!!!!!! All arrays must have same dimensions!!!!!

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [61]:
imH=numpy.hstack((im_g, im_g, im_g))
print(imH.T)

[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]
 [187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]
 [187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]


In [62]:
imV=numpy.vstack((im_g, im_g, im_g))
print(imV.T)

[[187 198 209 187 198 209 187 198 209]
 [158 125 134 158 125 134 158 125 134]
 [104 255 255 104 255 255 104 255 255]
 [121 255  97 121 255  97 121 255  97]
 [143 147 182 143 147 182 143 147 182]]


*** Splitting Numpy Arrays ***

In [67]:
lst_h = numpy.hsplit(imH, 3)
lst_h

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [69]:
lst_v = numpy.hsplit(imV, 5)
lst_v

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]